#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""Generate the deterministic Metatron source-art edition of BASM-NANO."""

import argparse
import hashlib
import math
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CANONICAL = ROOT / "basm-nano" / "basm_nano.c"
OUTPUT = ROOT / "basm-nano" / "basm_sacred.c"
WIDTH = 117
HEIGHT = 57


class Canvas:
    def __init__(self, width, height):
        self.width = width
        self.height = height
        self.cells = [[" " for _ in range(width)] for _ in range(height)]

    def put(self, x, y, char, overwrite=False):
        if 0 <= x < self.width and 0 <= y < self.height:
            old = self.cells[y][x]
            if overwrite or old == " ":
                self.cells[y][x] = char
            elif old != char:
                self.cells[y][x] = "+"

    def text(self, x, y, value):
        for index, char in enumerate(value):
            self.put(x + index, y, char, overwrite=True)

    def line(self, start, end):
        x0, y0 = start
        x1, y1 = end
        dx = x1 - x0
        dy = y1 - y0
        steps = max(abs(dx), abs(dy))
        if steps == 0:
            return
        if abs(dx) > 2 * abs(dy):
            char = "-"
        elif abs(dy) > 2 * abs(dx):
            char = "|"
        elif dx * dy < 0:
            char = "/"
        else:
            char = "\\"
        for step in range(steps + 1):
            x = round(x0 + dx * step / steps)
            y = round(y0 + dy * step / steps)
            self.put(x, y, char)

    def circle(self, center, rx, ry):
        cx, cy = center
        points = set()
        for dx in range(-rx, rx + 1):
            dy = math.isqrt(ry * ry * (rx * rx - dx * dx)) // rx
            points.add((dx, dy))
            points.add((dx, -dy))
        for dy in range(-ry, ry + 1):
            dx = math.isqrt(rx * rx * (ry * ry - dy * dy)) // ry
            points.add((dx, dy))
            points.add((-dx, dy))
        for dx, dy in points:
            if 2 * abs(dx) * ry > 3 * abs(dy) * rx:
                char = "|"
            elif 2 * abs(dy) * rx > 3 * abs(dx) * ry:
                char = "-"
            elif dx * dy < 0:
                char = "\\"
            else:
                char = "/"
            self.put(cx + dx, cy + dy, char, overwrite=True)

    def render(self):
        return ["".join(row) for row in self.cells]


def hexagon(cx, cy, rx, ry):
    half = rx // 2
    vertical = (ry * 866 + 500) // 1000
    return [(cx + rx, cy), (cx + half, cy + vertical),
            (cx - half, cy + vertical), (cx - rx, cy),
            (cx - half, cy - vertical), (cx + half, cy - vertical)]


def metatron():
    canvas = Canvas(WIDTH, HEIGHT)
    center = (WIDTH // 2, HEIGHT // 2)
    inner = hexagon(*center, 20, 10)
    outer = hexagon(*center, 42, 21)

    # Metatron's cube: two hexagons, both interlaced triangles, radial axes,
    # and bridges between corresponding circles.
    for ring in (inner, outer):
        for index in range(6):
            canvas.line(ring[index], ring[(index + 1) % 6])
            canvas.line(ring[index], ring[(index + 2) % 6])
    for index in range(6):
        canvas.line(center, inner[index])
        canvas.line(center, outer[index])
        canvas.line(inner[index], outer[index])
        canvas.line(inner[index], outer[(index + 1) % 6])

    for point in outer:
        canvas.circle(point, 7, 3)
    for point in inner:
        canvas.circle(point, 6, 3)
    canvas.circle(center, 9, 4)

    canvas.text(center[0] - 4, center[1] - 1, "BASM-NANO")
    canvas.text(center[0] - 5, center[1] + 1, "3 / 6 / 9")
    canvas.text(center[0] - 6, 1, "512 BYTE SECTOR")
    canvas.text(center[0] - 7, HEIGHT - 2, "BYTE-IDENTICAL")
    canvas.text(2, center[1], "PM32")
    canvas.text(WIDTH - 8, center[1], "PAGING")
    return canvas.render()


def generated_source():
    digest = hashlib.sha256(CANONICAL.read_bytes()).hexdigest()
    art = metatron()
    border = "+" + "-" * WIDTH + "+"
    lines = [
        "/*",
        " * basm_sacred.c - executable Metatron source art for BASM-NANO.",
        " * SPDX-License-Identifier: BSD-3-Clause",
        " * Copyright (c) 2026, F E R M I ∞ H A R T <contact@fermihart.com>",
        " *",
        " * GENERATED by tools/generate_sacred_basm.py. Do not hand-edit.",
        " * The readable implementation remains basm_nano.c; this translation",
        " * unit is a deterministic artistic seal around that exact source.",
        f" * canonical-sha256: {digest}",
        " *",
        f" * {border}",
    ]
    lines.extend(f" * |{row}|" for row in art)
    lines.extend([
        f" * {border}",
        " */",
        "",
        "enum basm_sacred_seal",
        "{",
        "                                  SACRED_CENTER = 0x7C00,",
        "",
        "                 SACRED_THREE = 3,                 SACRED_SIX = 6,",
        "                                  SACRED_NINE = 9,",
        "",
        "          SACRED_RING = 256,                              SACRED_SECTOR = 512,",
        "                                  SACRED_PAGE = 4096",
        "};",
        "",
        "#include \"basm_nano.c\"",
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if basm_sacred.c is not current")
    args = parser.parse_args()
    expected = generated_source()
    if args.check:
        actual = OUTPUT.read_bytes().decode("utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print("basm_sacred.c is stale; run tools/generate_sacred_basm.py",
                  file=sys.stderr)
            return 1
        print("sacred source: deterministic geometry is current")
        return 0
    OUTPUT.write_bytes(expected.encode("utf-8"))
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
